version: '3.8'

services:
  nextjs:
    build:
      dockerfile: ./nextjs/Dockerfile
    ports:
      - "3000:3000"

  nginx:
    build: 
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nextjs